version: '3'

services:
  # backend:
  #   build: 
  #     context: ./project-pokemon-flux-back
  #     dockerfile: Dockerfile
  #   command: yarn serve
  #   volumes:
  #     - ./project-pokemon-flux-back:/app
  #   ports:
  #     - "8080:8080"
  
  front:
    build: 
      context: ./project-pokemon-flux-front
      dockerfile: Dockerfile
    command: yarn watch
    volumes:
      - ./project-pokemon-flux-front:/app
      - /app/node_modules
    ports:
      - "4200:8080"
    # depends_on:
    #   - backend 
